title: Guida a Bitcoin per neofiti
email: aiuto-bitcoin@gionn.net
description: >
  Guida rapida per conoscere Bitcoin e come si usa
baseurl: "/"
url: "https://comprare-bitcoin.info"
google_analytics: UA-107557-22

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
